version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app

  mysql:
    image: mysql:8.0.30-debian
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: reports

  redis:
    image: redis:7.0.8-alpine
    ports:
      - '6379:6379'
